name: IMAGE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:      
      matrix:
        platform:
          - linux/arm64

    steps:
      - uses: actions/checkout@v2
                
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Configurar QEMU para emulação ARM
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install prerequisites
        run: |
          sudo apt-get update -y          

      - name: Login to OCI
        uses: docker/login-action@v3
        with:
          registry: sa-saopaulo-1.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Push docker image to OCI
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            sa-saopaulo-1.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/oci-demo:${{ github.run_number }}            
          file: ./Dockerfile
  